name: documentation
on:
  release:
    types:
      - published
  pull_request:
    branches:
      - main
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with docs
      
      - name: Build documentation
        run: |
          poetry run sphinx-apidoc -o docs/source google_books_api
          rm -rf docs/_build   # Clean build directory
          poetry run sphinx-build -b html docs/source docs/_build
      
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          force_orphan: true